# This file was generated by GoReleaser. DO NOT EDIT.
cask "paleo-git" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "3572da18b061028eb5ee192c0f5342e11c812d5338ede44b3bc0884a1e322bfe"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "932edcf839f194d8479c5311d95e5a8831debc53ebded58ff9f91b6881d2bdfc"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9d43e73358fe28fc70bcfcfe2c1dc4cb34ab4111f5ee8a690302f969fd7b799d"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "674249dedba3ff535aa73f3c213ec2114ece0399f90db876503e0464e49e8d6e"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_amd64.tar.gz"
    end
  end

  name "paleo-git"
  desc "Track code migration progress in git repositories"
  homepage "https://github.com/bel0v/paleo-git"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paleo-git"

  # No zap stanza required
end
