# This file was generated by GoReleaser. DO NOT EDIT.
cask "paleo-git" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "5e294c6a74cbc602f37f6d705762b32157e0f8e26654eafd2e3a661b80269a09"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49ffaa3e4619f724e6da0f4fd1d152b3787da86b2ac7d8f8ff028dd25077fa18"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f88fb2bcc9dbdf15d71685bbc4d7bcbd8b2ede1dcae15e31c96dbe661fc3f81d"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7756933a0f7f86523eed0db550fccdf84fee7be5a21be172f36cfc7766ab528a"
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_amd64.tar.gz"
    end
  end

  name "paleo-git"
  desc "Track code migration progress in git repositories"
  homepage "https://github.com/bel0v/paleo-git"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paleo-git"

  # No zap stanza required
end
