# This file was generated by GoReleaser. DO NOT EDIT.
cask "paleo-git" do
  name "paleo-git"
  desc "Track code migration progress in git repositories"
  homepage "https://github.com/bel0v/paleo-git"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paleo-git"

  on_macos do
    on_intel do
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_amd64.tar.gz"
      sha256 "7711ae6a445000f21db9a55cc67e0747f8e57a2b28df16582cf23bb902496ce1"
    end
    on_arm do
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_darwin_arm64.tar.gz"
      sha256 "c7633562ae7efe87f8c7126db608ca91f49ee3493ae8af93fe4b07ac7a4f5a1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_amd64.tar.gz"
      sha256 "96bc784c148327a5e4dcd5f922cf3fc8543aa139e108e00e9b8f49624bfad0b3"
    end
    on_arm do
      url "https://github.com/bel0v/paleo-git/releases/download/v#{version}/paleo-git_linux_arm64.tar.gz"
      sha256 "016dc54eea1e4bfa9648a673610753bf659151278ebc5b94be612ceacf53073c"
    end
  end

  # No zap stanza required
end
